language: java

jdk:
  - oraclejdk7
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "tlrTl4TBfpEFhxSW1/y5HAiSpeAgoN+DCXPJfw7TqnZqbzXk8wx5+KizR41IYj8ccYp5B9g1kD025l+8xFjGk80t7H6xESgU2vWlv1oAOMIGaJKnzNBXitFLrbqyd0mJMDyOGLbrEsbUeztWsodNsocNXmad/Mj0nOvk8pTt2uTGeWpY/gaF4LX1ivPDqdFjexjYZroSvofF+uWhIRN9m1Y5Jyx87rlqkdnUnAtVMgkEzvJO9v4OAD9HsxPwP7dNa8pc6AC8Bc9TLK6VOWqty4MSGA11vV/hRcNQqP9wRif1LnWC7F7rfFNFR1xk4gsXYZ/KT8HzgTpLs8tifw7qEFZ1n/qg8YrvZFUY3TycwK1sfs76wEsC+E33XSdP+KAfSvRFmhOra83eHajQYP1tJN6lFTOp8vXMqe4U9NwSeW4QIRk7vzdky1RltPTS955bPhwSn9Ynm4XG0SUjuv0fZKd3PpQbPotVHmGji45jSh6FfS3oSWoqLHyJoj1ya8qsM6vC3Gq+sfe+OnpgR8aetfLgvDVIAmz7d8A8Q8kHex8jsVSwzdtrFOJDU8pBUB72xL2SjE6Hk4/ow6xFeOwiKAfy2d3TK7rFb1YIzr8rYDlAhrwlAdr4iH1EIhqtzoXw0nyF6NaGq/PfnIjzo1LFEm0nOrPHpwDeV/8Xrl6tQW8="
    - secure: "Du3YpIwJNuyJcdjLC8T9VbqgUVBkCEdGuc3OGYR//KNr7X6WdpDKnwgSatFbi268X5KSukcDAiUabi5aAY28ysAkFBVpTtFm43x+uQRtGitE0sKoTnDfMRDXznPCDwDyB+MK+ZfIFBChJY97gzL74KGBN1aCo0/E9OJoH1XzJFPOlixTo8oN4AlVBs4Y0A6opLZSNf1D+YMb3g7Qj773jrpxnfxikI4JDD/5fSnGitk9kiPkpIFo1Tu705hyNnrj0y3SdhG7CaiE22JRR2MvugTwDFJQTqPlZJ/kB4wQ/CN0o7ACfie+DfewadWG79FQeCSb1fbk4pev/uzw4sSaavUTu2Nnxhw5XS+0npHrOD+Tev/nBtB19tpFOtEKNKWePax1MM0pISzAPkPAPElwTcjcqT5xCER3IAYmZLxQMUyyAMKhg7VneAjHS9AnCC/e7eryMJI2dUPNhzOKfMhupwKWgR9l+ckV+PBLRfoefQCoRtzcOXQwuZh8iwg2uNagmx8DT+usvBHuhBekHHFJVnNYZukLxwAOikXfNDHoH+GzVDP/9S8v0zFTeP0/WetmPkHbal+l6pn9rUcooKDSamtckzevsrjr9Kt6Y40NnyQf7DHNIqFk++AFp0oLSsMYWTVWa7PZhUnSedIj9CSGOyB6cvq/tHabR2LsL+h4vAA="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
