language: java

jdk:
  - oraclejdk7
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "oisTI+IzfslNaddoQijjq5XxP0ef3ZS070Gg3q1lyEu9q6MLf+hz8YVyn7q85KnYhRepIuJIPpyA92lf27QYVwV4LfrCy4hEcqA0favWWrAiZe5mBEW4PpYEDDsL4lBXvyUaEc3+cZaeFr+hs2VUleYq+QpU1GCncbQEyMMekUhy1b/w+wKFDZRJIm393BjN79k7WVuHY5Gon/T7Zaw3stdWntSRYekMJ384r3ZgZpJQHBInNCKAr+ykh9mQtqOkZNP66FO8N1BUJ1bUXWk7EYfhaF1NdXBVUNY9aftngevVKcY5tJM8uR0FcXH9vv5o1zSFYnIDkc+uMKOFXIhSIRJWdyyaJ1It0D96x8MYXFlM96XmzpZCPmFuduGBlMDVBf/Z90ElsWaUEw94QP7qzEqdVje3RVeG6sMMCCvZ9QLpYqI63ReXPdZKf/FBPmYVBLQUg33BdlfSiNjds0kN3oGQPKwFp5UxBo+R2xE2Q+/LYEmuTt/6WasQtDVMvLjs6xv2Jr/euinXnA8j6lxX/JOKFZlIdHf5XpjRjkEeeoHaQdaRjPI9SYVTNfQd2oWBd2Z0XBLgmDIPJuhUFqb2qqY42Qi9y6lnzp3bryfA7w0hUjU2T0pkHsEprIKpUEmenIuQh4VCYkROoAtsXrIli2mhDOZzJyKSF65r0Ud7itM="
    - secure: "ElC1jh5gmVeypdw/e/ZaFqD0XNBoWreg3v++8QJb5KcEF/qcwmxH+ashic2vrYgp/aH7NBX6x+5Iw9dERJDvAYP+x2qG2+iEqcuRKhWhdgGxSbQXSEF7CEpt1WnihjbRYykxiqt0XMs1kOB7U0cjV/sfbjIfT2hLAjmmUjnynjctEO9+PVZWO4KhjAt+lU1Q1Q3RjQRt8PbJsdo1XVajKdXkzfcwXFZc4f58HQfhdZDk/JDG/2u6mC09S1HNDmZFgmXFRaUJwyE5vfxn0soBQNwuGgD38L8z2VG8nUrPKeJz6xDRX7SnSKIiXRYclh4XOdCu51JTn9lOjmnGtgFoaQdyXMCuMYQwFQv491J4n1JcAIlbUM4zmWutuFhy0Z/yS+LLkFhwX/bu3BjwHGrtZNJQUcBMpELQ3FqfQpVt4ywg0wgMbn3h9S32tmynuGTGMD3IBG6yvE0GgTAxnUkiCNH95QcKmitUXESFpXN/Fki02MuBz07d4vZjymyBR3vHkDKaH6gG/Xy/nwTYtlCYIuCQNjhj3TJ5Toes08barQ+WQtI3qkCGZwzh8oHIKbue8gxpejwcp4cg3PDUg80igO1oI0zYQ5Fh9ATxDdydfZ8RRIVgveicni5KgSqVdA+ypE/socO7u7hxGVmLPCUMBpDe56vgoAh4SgtfW27gA6A="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
