[libraries]
kotlinPlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.21"
mavenPublishPlugin = "com.vanniktech:gradle-maven-publish-plugin:0.34.0"

rxjava2 = "io.reactivex.rxjava2:rxjava:2.2.21"

junit = "junit:junit:4.13.2"
